version: 2.0

workflows:
  version: 2
  test:
    jobs:
      - rspec
      - rubocop

jobs:
  rspec:
    working_directory: ~/profile_app
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - run: sudo gem update --system
      - run: sudo gem install bundler -v 2.1.2
      - run: bundle install --path vendor/bundle
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

  rubocop:
    working_directory: ~/profile_app
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - run: sudo gem update --system
      - run: sudo gem install bundler -v 2.1.2
      - run: bundle install --path vendor/bundle
      - type: shell
        command: |
          bundle exec rubocop

  deploy:
    working_directory: ~/profile_app
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - type: shell
        command: |
          git push https://heroku:31bef4bb-ce5d-4ae8-936a-be40f9cae50c@git.heroku.com/profile-app-dro.git master
