version: 2.0

# orbs:
#   ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

workflows:
  version: 2
  test:
    jobs:
      - rspec
      - rubocop:
        requires:
          - rspec

jobs:
  rspec:
    working_directory: ~/profile_app
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - run: sudo gem update --system
      - run: sudo gem install bundler -v 2.1.2
      - run: bundle install --path vendor/bundle
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
  rubocop:
    working_directory: ~/profile_app
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - run: sudo gem update --system
      - run: sudo gem install bundler -v 2.1.2
      - run: bundle install --path vendor/bundle
      - type: shell
        command: |
          bundle exec rubocop
