version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

workflows:
  version: 2
  test:
    jobs:
      - rspec

jobs:
  rspec:
    steps:
      - run: sudo gem update --system
      - run: sudo gem install bundler -v 2.1.2
      - run: bundle install
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
            path: test_results
