version: 2.0

# orbs:
#   ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

workflows:
  version: 2
  test:
    jobs:
      - rspec

jobs:
  rspec:
    working_directory: ~/profile_app
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
          sudo gem update --system
          sudo gem install bundler -v 2.1.2
      - run: bundle install --path vendor/bundle
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
            path: test_results
