version: 2

workflows:
  version: 2
  test:
    jobs:
      - rubocop
      - rspec:
        requires:
          - rubocop
      - deploy:
        requires:
          - rspec
executors:
  rspec:
    working_directory: ~/profile_app
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          RAILS_ENV: test
  rubocop:
    working_directory: ~/profile_app
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          RAILS_ENV: development
jobs:
  rspec:
    executor: rspec
    steps:
      - run: sudo gem update --system
      - run: sudo gem install bundler -v 2.1.2
      - run: bundle install
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
            path: test_results
  rubocop:
    executor: rubocop
    steps:
      - run: bundle install
      - type: shell
        command: |
          bundle exec rubocop

  deploy:
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:31bef4bb-ce5d-4ae8-936a-be40f9cae50c@git.heroku.com/profile-app-dro.git master

